language: python
sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
#   - TOxENV=pypy3
#   pending 3.3-compatible release
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
